# Generated by Django 4.1.4 on 2022-12-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
