# Generated by Django 4.1.4 on 2022-12-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='active',
            field=models.CharField(max_length=10),
        ),
    ]
