# Generated by Django 4.1.4 on 2022-12-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_level_alter_student_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dept',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
