# Generated by Django 4.1.4 on 2022-12-26 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_graduatedstudent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
