# Generated by Django 4.1.4 on 2022-12-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_delete_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phone_Num',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
